services:
  API:
    build:
      context: .
      dockerfile: Dockerfile.Back
    image: fr
    container_name: back
    ports:
      - "5000:5000"
  front:
    build:
      context: .
      dockerfile: Dockerfile.Front
    image: ba
    environment:
      DockHost: "back"
    container_name: front
    ports:
      - "8501:8501"
