#!/bin/bash

# Start Streamlit app in a new terminal window
gnome-terminal -- bash -c "streamlit run app.py; exec bash"

# Start Python app in a new terminal window
gnome-terminal -- bash -c "python3 api.py; exec bash"

